# Generated by Django 5.0 on 2024-01-14 20:47

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_client_client_address_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_issue_date', models.DateField(verbose_name='issue date')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='invoice number')),
                ('invoice_status', models.CharField(choices=[('0', 'DELETE'), ('1', 'DRAFT'), ('2', 'SENT'), ('4', 'REVISE'), ('5', 'PAID')], max_length=150, verbose_name='status')),
                ('invoice_total_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('invoice_total', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, verbose_name='total')),
                ('invoice_date_created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('invoice_date_modified', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('item_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='description')),
                ('item_quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='quantity')),
                ('item_price_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('item_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, verbose_name='unit price')),
                ('item_total_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('item_total', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=14, verbose_name='total')),
                ('invoice_date_created', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('invoice_date_modified', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
            ],
        ),
    ]
