# Generated by Django 5.0 on 2024-01-19 17:30

import djmoney.models.fields
import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice_date_created',
            new_name='item_date_created',
        ),
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice_date_modified',
            new_name='item_date_modified',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=invoices.models.next_invoice_number, max_length=50, unique=True, verbose_name='invoice number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('0', 'DELETE'), ('1', 'DRAFT'), ('2', 'SENT'), ('3', 'REVISE'), ('4', 'PAID')], max_length=150, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_total',
            field=djmoney.models.fields.MoneyField(currency_choices=(('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')), decimal_places=2, default_currency='USD', max_digits=14, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_description',
            field=models.TextField(default='', max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_price',
            field=djmoney.models.fields.MoneyField(currency_choices=(('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')), decimal_places=2, default_currency='USD', max_digits=14, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_total',
            field=djmoney.models.fields.MoneyField(currency_choices=(('GBP', 'British Pound'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('INR', 'Indian Rupee'), ('USD', 'US Dollar')), decimal_places=2, default_currency='USD', max_digits=14, verbose_name='total'),
        ),
    ]
