# Generated by Django 5.0 on 2024-01-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_rename_invoice_date_created_invoiceitem_item_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_total_currency',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item_price_currency',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item_total_currency',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='unit price'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_total',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total'),
        ),
    ]
