# Generated by Django 5.0 on 2024-05-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('1', 'DRAFT'), ('2', 'SENT'), ('3', 'REVISED'), ('4', 'PAID'), ('5', 'DELETED'), ('6', 'CANCELLED')], max_length=150, verbose_name='status'),
        ),
    ]
