# Generated by Django 5.0 on 2024-01-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('client_date_modified', models.DateField(auto_now=True, verbose_name='date modified')),
                ('client_name', models.CharField(blank=True, default='', max_length=150, verbose_name='name')),
                ('client_address_1', models.CharField(blank=True, default='', max_length=150, verbose_name='address line 1')),
                ('client_address_2', models.CharField(blank=True, default='', max_length=150, verbose_name='address line 2')),
                ('client_zip', models.CharField(blank=True, default='', max_length=100, verbose_name='zip')),
                ('client_phone', models.CharField(blank=True, default='', max_length=100, verbose_name='phone')),
                ('client_fax', models.CharField(blank=True, default='', max_length=100, verbose_name='fax')),
                ('client_mobile', models.CharField(blank=True, default='', max_length=100, verbose_name='mobile')),
                ('client_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('client_web', models.CharField(blank=True, default='', max_length=200, verbose_name='website')),
                ('client_currency', models.CharField(max_length=50, verbose_name='currency')),
                ('client_active', models.BooleanField(verbose_name='active')),
                ('client_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.city', verbose_name='city')),
                ('client_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.country', verbose_name='country')),
                ('client_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.region', verbose_name='state/province')),
            ],
        ),
    ]
