# Generated by Django 5.0 on 2024-01-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_address_1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_address_2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_state',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_zip',
        ),
        migrations.AddField(
            model_name='client',
            name='client_address',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='', max_length=150, verbose_name='client name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_web',
            field=models.CharField(default='', max_length=200, verbose_name='website'),
        ),
    ]
